views:
  - output: "index.html"
    query: "select/artists-books.rq"
    template: "index.html"
  - output: "item/{{id}}/index.html"
    query: "select/artists-books.rq"
    template: "artists-book.html"
