views:
  - output: "index.html"
    query: "select/artists-books.rq"
    template: "index.html"
  - output: "item/{{itemKey}}/index.html"
    query: "select/artists-books.rq"
    template: "artists-book.html"
  - output: "references.html"
    query: "select/references.rq"
    template: "references.html"
  - output: "reference/{{itemKey}}/index.html"
    query: "select/references.rq"
    template: "reference.html"
