PREFIX ab:      <https://dkglab.github.io/ns/artists-books/>
PREFIX bf:      <http://id.loc.gov/ontologies/bibframe/>
PREFIX bflc:    <http://id.loc.gov/ontologies/bflc/>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd:      <http://www.wikidata.org/entity/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT
  ?book
  ?title
  ?itemKey
  (GROUP_CONCAT(DISTINCT ?primaryCreatorDisplay; separator="; ") AS ?primaryCreators)
  (GROUP_CONCAT(DISTINCT ?otherCreatorDisplay; separator="; ") AS ?contributors)
  ?publisher
  ?place
  ?date
  ?language
  ?extent
  ?dimensions
  (GROUP_CONCAT(DISTINCT ?isbn; separator="; ") AS ?isbns)
  (GROUP_CONCAT(DISTINCT ?oclc_number; separator="; ") AS ?oclcNumbers)
  (SAMPLE(?worldcat_url) AS ?worldcatLink)
WHERE {
  ?book
    a ab:ArtistsBook ;
    rdfs:label ?title ;
    ab:itemKey ?itemKey ;
    .

  OPTIONAL {
    ?book bf:contribution ?c .
    ?c a bflc:PrimaryContribution ;
       bf:agent ?agent .
    ?agent rdfs:label ?name .
    OPTIONAL { ?c bf:role/rdfs:label ?role . }
    BIND(
      IF(BOUND(?role),
         CONCAT(?name, " [", ?role, "]"),
         ?name
      ) AS ?primaryCreatorDisplay
    )
  }

  OPTIONAL {
    ?book bf:contribution ?c2 .
    ?c2 a bf:Contribution ;
        bf:agent ?agent2 .
    ?agent2 rdfs:label ?name2 .
    OPTIONAL { ?c2 bf:role/rdfs:label ?role2 . }
    BIND(
      IF(BOUND(?role2),
         CONCAT(?name2, " [", ?role2, "]"),
         ?name2
      ) AS ?otherCreatorDisplay
    )
  }

  OPTIONAL {
    ?book bf:provisionActivity ?pub .
    OPTIONAL { ?pub bflc:simpleAgent ?publisher . }
    OPTIONAL { ?pub bflc:simplePlace ?place . }
    OPTIONAL { ?pub bflc:simpleDate  ?date . }
  }

  OPTIONAL { ?book bf:language ?language . }

  OPTIONAL {
    ?book bf:extent ?extentNode .
    ?extentNode rdfs:label ?extent .
  }

  OPTIONAL {
    ?book bf:dimensions ?dimensions .
  }

  OPTIONAL {
    ?book bf:identifiedBy ?id .
    ?id rdf:value ?isbn ;
        bf:source wd:Q33057 .
  }

  OPTIONAL {
    ?book bf:identifiedBy ?oclcId .
    ?oclcId rdf:value ?oclc_number ;
            bf:source wd:Q846596 .
  }

  OPTIONAL {
    ?book foaf:isPrimaryTopicOf ?worldcat_url .
  }
}
GROUP BY ?book ?title ?itemKey ?publisher ?place ?date ?language ?extent ?dimensions
ORDER BY LCASE(?title)
