PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX ab: <https://dkglab.github.io/ns/artists-books/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
PREFIX bflc: <http://id.loc.gov/ontologies/bflc/>
PREFIX wd: <http://www.wikidata.org/entity/>

CONSTRUCT {
  ?book a ab:ArtistsBook ;
    rdfs:label ?title ;
    ab:itemKey ?item_key ;
    bf:title ?bookTitle ;
    bf:contribution [
      a bf:Contribution ;
      bf:agent ?creator ;
    ] ;
    bf:provisionActivity ?bookPublication ;
    bf:language ?language ;
    bf:identifiedBy ?bookIdentifier ;
    .

  ?bookTitle a bf:Title ;
    bf:mainTitle ?title ;
    .

  ?bookPublication a bf:Publication ;
    bflc:simpleAgent ?publisher ;
    bflc:simpleDate ?date ;
    bflc:simplePlace ?place ;
    .

  ?bookIdentifier a bf:Identifier ;
    rdf:value ?ISBN ;
    bf:source wd:Q33057 ; # ISBN
    .

  ?creator a bf:Agent ;
    rdfs:label ?creator_name ;
    .

}
WHERE {
  SERVICE <x-sparql-anything:location=Zotero/artists-books.csv> {
    fx:properties
      fx:csv.headers "true" ;
      fx:csv.null-string  "" ;
      .

    ?bookRow
      xyz:itemKey ?item_key ;
      xyz:title ?title ;
      xyz:publisher ?publisher ;
      xyz:date ?date_raw ;
      .

    # Strip Zotero's leading "YYYY-MM-DD " prefix from the date string
    BIND(REPLACE(?date_raw, "^\\d{4}-\\d{2}-\\d{2} ", "") AS ?date)

    # Mint new book URIs using the fx:entity function
    BIND(fx:entity(ab:, "item/", ?item_key) AS ?book)
    BIND(fx:entity(ab:, "item/", ?item_key, "/title") AS ?bookTitle)
    BIND(fx:entity(ab:, "item/", ?item_key, "/publication") AS ?bookPublication)

    OPTIONAL {
      ?bookRow xyz:place ?place
    }
    OPTIONAL {
      ?bookRow xyz:language ?language
    }
    OPTIONAL {
      ?bookRow xyz:ISBN ?ISBN
      BIND(fx:entity(ab:, "item/", ?item_key, "/identifier") AS ?bookIdentifier)
    }
  }

  SERVICE <x-sparql-anything:location=Zotero/all-creators-reconciled.csv> {
    fx:properties fx:csv.headers "true" .

    ?creatorRow
      xyz:creatorID ?creator_id ;
      xyz:name ?creator_name ;
      .

    # Mint new creator URI using the fx:entity function
    BIND(fx:entity(ab:, "creator/", ?creator_id) AS ?creator)
  }

  SERVICE <x-sparql-anything:location=Zotero/all-item_creators.csv> {
    fx:properties fx:csv.headers "true" .

    ?joinRow
      xyz:itemKey ?item_key ;
      xyz:creatorID ?creator_id ;
      xyz:creatorType ?creator_type ;
      .
  }
}
