views:
  - output: "index.html"
    query: "artists-books.rq"
    template: "index.html"
  - output: "item/{{itemKey}}/index.html"
    query: "artists-books.rq"
    template: "artists-book.html"
  - output: "references.html"
    query: "references.rq"
    template: "references.html"
  - output: "reference/{{itemKey}}/index.html"
    query: "references.rq"
    template: "reference.html"
  - output: "construction.html"
    query: "construction-methods.rq"
    template: "construction-methods.html"
  - output: "construction/{{conceptKey}}/index.html"
    query: "construction-methods.rq"
    template: "construction-method.html"
  - output: "subjects.html"
    query: "subjects.rq"
    template: "subjects.html"
  - output: "subject/{{conceptKey}}/index.html"
    query: "subjects.rq"
    template: "subject.html"
